layout_spectrum: 0.9228545983787626
typography_spectrum: 0.15432378859259188
color:
  saturation: 0.6667064644861966
  brandStrength: 0.5016689253970981
  rhythmicContrast: 0.6502146595157683
  brandColors:
    - '#F0EDE8'
    - '#32312F'
    - '#B2AB9C'
    - '#40629F'
    - '#A64E59'
  lightness: 0.030098324874415994
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: gushyglobal
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: NO PARKING
purpose: []
